name: Daily WhatsApp Reminder

on:
  schedule:
    - cron: '0 7 * * *'  # tous les jours à 07h UTC (8h heure de Paris)
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib twilio

      - name: Create service account file
        run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > service-account.json

      - name: Run script
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TO_WHATSAPP: ${{ secrets.TO_WHATSAPP }}
        run: python calendar_whatsapp.py
